#goal definition
# int32[] Pos
string order 
#0 - INIT 1 - GO 2 - PAUSE 
---
#result definition
string sequence
#[current position]
#[Used Time]
---
#feedback
string sequence

#[current position]
#[current order num]
#[current ordered position]
#[running time]
#[estimated arrirve time]

# #goal definition
# int32 order
# ---
# #result definition
# int32[] sequence
# ---
# #feedback
# int32[] sequence